apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sbqv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-sbqv@sha256:31c965c31aa5f104aa2b628c0e6d188dae2238f560fa61e2b5838c7dfab6f225
        name: my-nodejs
        resources: {}
status: {}
